version: 2
jobs:
  build:
    working_directory: /go/src/github.com/upamune/hugo-amazon-api
    docker:
      - image: upamune/hugo-amazon-api-ci
    steps:
      - checkout
      - run:
          name: install deps
          command: glide install
      - run:
          name: build
          command: go build
      - run:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              gox -ldflags "-w -s" -output "dist/ncd_{{.OS}}_{{.Arch}}"
              ghr -t $GITHUB_TOKEN -u upamune -r hugo-amazon-api --replace $(git describe --tags) dist/
            fi
